#define OSO_START_R 0x0
#define OSO_STOP_R 0x100
#define OSO_STATUS_R 0x200
#define OSO_DATA_R 0x300
#define OSO_SETFPGA_R 0x400
#define OSO_PARA_R 0x500

#define OSO_PROCESS_R 0x900
#define OSO_SUPER_R 0x10000
#define OSO_NEW_PROTOCOL_R 0x20000



#define OSOSTART 0|OSO_START_R
#define OSORESTART 1|OSO_START_R
#define OSORESUME 2|OSO_START_R
#define OSOSTARTSAVEFILE 3|OSO_START_R
#define OSOSTOPSAVEFILE 5|OSO_START_R
#define OSOCRES 6|OSO_START_R




#define OSOSTOP 0|OSO_STOP_R
#define OSOPAUSE 1|OSO_STOP_R
#define OSOEXIT 2|OSO_STOP_R
#define OSOPOWEROFF 3|OSO_STOP_R 
#define OSOREBOOT 4|OSO_STOP_R 



#define OSOGETINFO 0|OSO_STATUS_R
#define OSOGETPARA 1|OSO_STATUS_R


#define OSOGETDATA 2|OSO_DATA_R
#define OSOCLOSEDATA 3|OSO_DATA_R


#define OSOSPISETPARA 1|OSO_SETFPGA_R
#define OSOSPIGETINFO 2|OSO_SETFPGA_R
#define OSOSPIGETSTATUS 3|OSO_SETFPGA_R
#define OSOSPITEST 4|OSO_SETFPGA_R
#define OSOSPITEST_READ 5|OSO_SETFPGA_R
#define OSOSPITEST1 6|OSO_SETFPGA_R
#define OSOSPIEN_AD 7|OSO_SETFPGA_R
#define OSOSPIUEN_AD 8|OSO_SETFPGA_R



#define OSODODEFAULT 1|OSO_PARA_R
#define OSOPARATEST 2|OSO_PARA_R

#define OSO_CMD_PROCESS 0|OSO_PROCESS_R

#define OSO_ENABLE_TELNET OSO_SUPER_R|0
#define OSO_DISABLE_TELNET OSO_SUPER_R|1
#define OSO_UPDATE_ALL OSO_SUPER_R|2//通过上位机软件跟新全部
#define OSO_UPDATE_ACQ_FROMNET OSO_SUPER_R|3//通过网络更新采集程序
#define OSO_UPDATE_ACQ OSO_SUPER_R|4//通过上位机软件跟新全部

#define OSO_CHANGE_SUPER_USER OSO_SUPER_R|100
#define OSO_CHANGE_USER OSO_SUPER_R|101



#define OSO_DISPLAY_BUFSHOW OSO_SUPER_R|200
#define OSO_CHANGE_FILESIZE OSO_SUPER_R|300


//config
#define OSO_READ_CONF_VALUE OSO_SUPER_R|400
#define OSO_WRITE_CONF_VALUE OSO_SUPER_R|401


//new protocol
#define OSO_NEW_READ_CONF_VALUE OSO_NEW_PROTOCOL_R|0




#define RUN_STATUS_RUN 1
#define RUN_STATUS_STOP 0
#define RUN_STATUS_PAUSE 2 
#define RUN_STATUS_ERR 3
